name: Prettier
on: [push]

jobs:
  Prettify-Code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "7.16.0"
        
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      
      - name: Format Code
        run: pnpm run format

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "refactor(action): formatting"